services:
  airflow:
    build:
      context: ../..
      dockerfile: orchestration/airflow/Dockerfile
    command: standalone
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__PARALLELISM: "1"
      AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: "1"
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: "1"
      AIRFLOW__DAG_PROCESSOR__PARSING_PROCESSES: "1"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      SOD_ENV: local
      SOD_WAREHOUSE: /opt/sod-platform/data/warehouse
      SPARK_MASTER: local[1]
      SPARK_LOCAL_IP: 127.0.0.1
    env_file: .env
    ports: ["8080:8080"]
    volumes:
      - ./dags:/opt/airflow/dags:ro
      - ../../logs/airflow:/opt/airflow/logs
      - ../../data/raw:/opt/sod-platform/data/raw:ro
      - ../../data/warehouse:/opt/sod-platform/data/warehouse
      - ../../configs:/opt/sod-platform/configs:ro
      - ../../scripts:/opt/sod-platform/scripts:ro
      - ../../artifacts:/opt/sod-platform/artifacts
    mem_limit: ${AIRFLOW_MEMORY_LIMIT:-3g}
